Repository TomPotato/PavedWay, pull requests merged in 2025-06, with the labels that each got.

#27 Feature/UI events
  Backend/package-lock.json
  Backend/package.json
  Backend/src/app.js
  Backend/src/models/Duration.js
  Backend/src/models/Report.js
  Backend/src/routes/geocodeRoutes.js
  Backend/src/routes/index.js
  Backend/src/routes/reportRoutes.js
  Backend/src/routes/siteRoutes.js
  Backend/src/services/ReportService.js
  Backend/src/services/SiteService.js
  Backend/src/utils/Validator.js
  Backend/src/utils/distanceFilter.js
  Frontend/.gitignore
  Frontend/README.md
  Frontend/index.html
  Frontend/jsconfig.json
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/public/logo.png
  Frontend/public/logo_title.png
  Frontend/src/App.vue
  Frontend/src/assets/styles/main.css
  Frontend/src/assets/styles/variables.css
  Frontend/src/components/Navbar.vue
  Frontend/src/components/RedirectMessage.vue
  Frontend/src/main.js
  Frontend/src/pages/Events.vue
  Frontend/src/pages/Home.vue
  Frontend/src/pages/Login.vue
  Frontend/src/pages/Register.vue
  Frontend/src/routes/index.js
  Frontend/src/services/Api.js
  Frontend/src/services/AuthService.js
  Frontend/src/services/Nominatim.js
  Frontend/src/services/ReportService.js
  Frontend/src/services/SiteService.js
  Frontend/src/stores/authStores.js
  Frontend/src/utils/Validator.js
  Frontend/tailwind.config.js
  Frontend/vite.config.js
  swagger.yaml
Labels: enhancement, bug-fix

#28 Feature/comment event
  Backend/src/models/Comment.js
  Backend/src/models/Report.js
  Backend/src/routes/reportRoutes.js
  Backend/src/routes/siteRoutes.js
  Backend/src/services/ReportService.js
  Backend/src/services/SiteService.js
  Backend/src/utils/Validator.js
  swagger.yaml
Labels: enhancement

#31 Feature/UI events info
  Backend/src/routes/authRoutes.js
  Backend/src/routes/index.js
  Backend/src/routes/locationRoutes.js
  Backend/src/routes/pathRoutes.js
  Backend/src/routes/reportRoutes.js
  Backend/src/routes/siteRoutes.js
  Backend/src/routes/userRoutes.js
  Backend/src/services/PathService.js
  Backend/src/services/SiteService.js
  Backend/src/utils/Validator.js
  Backend/src/utils/distanceFilter.js
  Backend/src/utils/tokenChecker.js
  Frontend/index.html
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/public/aim.svg
  Frontend/public/favicon/android-chrome-192x192.png
  Frontend/public/favicon/android-chrome-512x512.png
  Frontend/public/favicon/apple-touch-icon.png
  Frontend/public/favicon/favicon-16x16.png
  Frontend/public/favicon/favicon-32x32.png
  Frontend/public/favicon/favicon.ico
  Frontend/public/favicon/site.webmanifest
  Frontend/public/logo.png
  Frontend/public/report.svg
  Frontend/public/road.svg
  Frontend/public/site.svg
  Frontend/src/App.vue
  Frontend/src/assets/styles/main.css
  Frontend/src/components/Map.vue
  Frontend/src/components/Navbar.vue
  Frontend/src/components/RedirectMessage.vue
  Frontend/src/main.js
  Frontend/src/pages/Events.vue
  Frontend/src/pages/Home.vue
  Frontend/src/pages/Login.vue
  Frontend/src/pages/Profile.vue
  Frontend/src/pages/Refresh.vue
  Frontend/src/pages/Register.vue
  Frontend/src/pages/ReportInfo.vue
  Frontend/src/pages/Users.vue
  Frontend/src/routes/index.js
  Frontend/src/services/Api.js
  Frontend/src/services/AuthService.js
  Frontend/src/services/MapService.js
  Frontend/src/services/Nominatim.js
  Frontend/src/services/PathService.js
  Frontend/src/services/UserService.js
  Frontend/src/stores/authStores.js
  README.md
  swagger.yaml
Labels: documentation, enhancement

#32 Feature/UI comment event
  Backend/src/services/SiteService.js
  Frontend/public/comment.svg
  Frontend/src/pages/Events.vue
  Frontend/src/pages/ReportInfo.vue
  Frontend/src/services/ReportService.js
  Frontend/src/services/SiteService.js
Labels: documentation, enhancement, ui-enhancement

#35 Feature/UI create admin
  Backend/src/models/Notification.js
  Backend/src/routes/notificationRoutes.js
  Backend/src/routes/reportRoutes.js
  Frontend/src/components/Navbar.vue
  Frontend/src/pages/Events.vue
  Frontend/src/pages/Profile.vue
  Frontend/src/pages/UserInfo.vue
  Frontend/src/pages/Users.vue
  Frontend/src/routes/index.js
  Frontend/src/services/UserService.js
  Frontend/src/stores/authStores.js
Labels: documentation, enhancement, ui-enhancement

#36 Updated user routing paths and removed console log from findUserById …
  Frontend/src/pages/Users.vue
  Frontend/src/routes/index.js
  Frontend/src/services/UserService.js
Labels: bug-fix
