Repository TomPotato/PavedWay, pull requests merged in 2025-05, with the labels that each got.

#2 Revisione "Read Reports"
  .gitignore
  Backend/package-lock.json
  Backend/package.json
  Backend/server.js
  Backend/src/app.js
  Backend/src/config/paths.js
  Backend/src/database/DatabaseClient.js
  Backend/src/models/Comment.js
  Backend/src/models/Duration.js
  Backend/src/models/Event.js
  Backend/src/models/Location.js
  Backend/src/models/Report.js
  Backend/src/routes/index.js
  Backend/src/routes/reportRoutes.js
  Backend/src/services/ReportService.js
  Backend/src/utils/createError.js
  Backend/src/utils/toValidInt.js
  swagger.yaml
Labels: enhancement

#6 Implementazione metodo REST: Login
  Backend/package-lock.json
  Backend/package.json
  Backend/src/models/Admin.js
  Backend/src/models/Citizen.js
  Backend/src/models/User.js
  Backend/src/routes/authRoutes.js
  Backend/src/routes/index.js
  Backend/src/routes/reportRoutes.js
  Backend/src/routes/siteRoutes.js
  Backend/src/services/AuthService.js
  Backend/src/services/ReportService.js
  Backend/src/services/SiteService.js
  Backend/src/services/UserService.js
  Backend/src/utils/tokenChecker.js
  swagger.yaml
Labels: enhancement

#7 Implementazione metodo REST: Register
  Backend/src/models/Citizen.js
  Backend/src/models/User.js
  Backend/src/routes/authRoutes.js
  Backend/src/services/AuthService.js
  Backend/src/services/ReportService.js
  Backend/src/services/SiteService.js
  Backend/src/utils/Validator.js
  swagger.yaml
Labels: enhancement

#12 Feature/create report
  Backend/src/routes/reportRoutes.js
  Backend/src/services/ReportService.js
  swagger.yaml
Labels: enhancement

#9 Register e Login ora restituiscono anche informazioni sull'utente.
  Backend/src/routes/authRoutes.js
  Backend/src/services/AuthService.js
  swagger.yaml
Labels: bug, enhancement

#15 Feature/update sites
  Backend/src/routes/siteRoutes.js
  Backend/src/services/SiteService.js
  swagger.yaml
Labels: enhancement, question

#16 Feature/delete report
  Backend/src/routes/reportRoutes.js
  Backend/src/routes/siteRoutes.js
  Backend/src/services/ReportService.js
  Backend/src/services/SiteService.js
  swagger.yaml
Labels: enhancement

#17 Implementazione metodo REST: Read Sent Reports
  Backend/src/models/Report.js
  Backend/src/routes/index.js
  Backend/src/routes/reportRoutes.js
  Backend/src/routes/userRoutes.js
  Backend/src/services/ReportService.js
  Backend/src/services/SiteService.js
  Backend/src/services/UserService.js
  swagger.yaml
Labels: enhancement

#18 Implementazione metodo REST: Create User
  Backend/src/models/Admin.js
  Backend/src/models/Citizen.js
  Backend/src/routes/authRoutes.js
  Backend/src/routes/reportRoutes.js
  Backend/src/routes/siteRoutes.js
  Backend/src/routes/userRoutes.js
  Backend/src/services/AuthService.js
  Backend/src/services/SiteService.js
  Backend/src/services/UserService.js
  swagger.yaml
Labels: enhancement

#13 Feature/read reports datefilter
  Backend/src/routes/reportRoutes.js
  Backend/src/routes/siteRoutes.js
  Backend/src/services/ReportService.js
  Backend/src/services/SiteService.js
  Backend/src/utils/Validator.js
  swagger.yaml
Labels: documentation, enhancement, help wanted

#19 Revert "Feature/read reports datefilter"
  Backend/src/routes/reportRoutes.js
  Backend/src/routes/siteRoutes.js
  Backend/src/services/ReportService.js
  Backend/src/services/SiteService.js
  Backend/src/utils/Validator.js
  swagger.yaml
Labels: documentation, enhancement, help wanted

#22 Freature/approve reports
  Backend/src/routes/reportRoutes.js
  Backend/src/routes/siteRoutes.js
  Backend/src/services/ReportService.js
  Backend/src/services/SiteService.js
  swagger.yaml
Labels: documentation, enhancement

#24 Feature/read sites datefilter
  Backend/src/services/ReportService.js
  Backend/src/services/SiteService.js
Labels: enhancement, bug-fix

#26 Feature/find direct path
  Backend/package-lock.json
  Backend/package.json
  Backend/src/routes/index.js
  Backend/src/routes/pathRoutes.js
  Backend/src/services/PathService.js
  Backend/src/utils/toValidFloat.js
  Backend/src/utils/toValidInt.js
  swagger.yaml
Labels: enhancement
